"""changed model field to prevent bug

Revision ID: 2209f290227f
Revises: 5f2bd5081d2e
Create Date: 2026-03-24 23:20:24.705637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2209f290227f'
down_revision: Union[str, Sequence[str], None] = '5f2bd5081d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('farm_status', sa.Enum('PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'PAID_OUT', 'REJECTED', 'DEADLINE_PASSED', 'CANCELLED', name='farmstatus'), nullable=False))
    op.add_column('farms', sa.Column('location_verified', sa.Boolean(), nullable=False))
    op.drop_column('farms', 'status')
    op.drop_column('farms', 'location_Verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('location_Verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('farms', sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'PAID_OUT', 'REJECTED', 'DEADLINE_PASSED', 'CANCELLED', name='farmstatus'), autoincrement=False, nullable=False))
    op.drop_column('farms', 'location_verified')
    op.drop_column('farms', 'farm_status')
    # ### end Alembic commands ###
